[auth]
redirect_uri = "http://localhost:8501/oauth2callback"
cookie_secret = "PuCBkaCuogt3Jg4vTYTXNLw4BaRPMENs2*BvYYybeZXiWMzNUjDz-GzMWeWzdU@B"
client_id = "YN4QTcTd5trHEfSI"
client_secret = "J1rrDDyaElAFUwSfHWqojFkCQTO9Non5"
server_metadata_url = "https://warm-urchin-46.clerk.accounts.dev/.well-known/openid-configuration"
client_kwargs = { "prompt" = "login" }
